PriceTracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('User.urls', namespace='user')),
    path('blog/', include('blog.urls')),
    path('', include('ProductsApp.urls', namespace="products")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_header = "R-MARKET ADMIN"
admin.site.site_title = "R-MARKET ADMIN"

ProductsApp/urls.py
from django.urls import path
from .views import (IndexView, ContactView, MyAccountView,
                    CheckoutView, CartView, ProductDetailView, ProductUpdateView, ShopList, ShopProducts,
                    add_to_wishlist,remove_from_wishlist, remove_from_cart,
                    add_to_cart, ProductCreateView, WishListView,
                    AboutUsView, CompaireView, CategoryListView,
                    add_to_compaire, MainSearch, TagView)
from .context_processors import EmailSub

app_name="products"

urlpatterns = [
    path("", IndexView, name="index"),
    path('shop/', ShopList, name="shop"),
    path('shop/<slug>/', ShopProducts, name="shop-products"),
    path('shop/merchant/add-product/', ProductCreateView, name="add-product"),
    path('about-us/', AboutUsView, name="about-us"),
    path('compare-specs/<user>/', CompaireView, name="compare"),
    path("cart/", CartView, name="cart"),
    path('product/<slug>/', ProductDetailView, name="product-detail"),
    path('product/<slug>/<int:pk>/', ProductUpdateView, name="product-update"),
    path('add-to-cart/<slug>/', add_to_cart, name="add-to-cart"),
    path('wishlist/<user>/', WishListView, name='wishlist'),
    path('remove-from-cart/<slug>/', remove_from_cart, name="remove-from-cart"),
    path("add-to-wishlist/<slug>/",add_to_wishlist, name="add-to-wishlist"),
    path("remove-fom-wishlist/<slug>/",remove_from_wishlist, name="remove-from-wishlist"),
    path("checkout/", CheckoutView, name="checkout"),
    path("contact", ContactView, name='contact'),
    path('view-product-by-category/<slug>/', CategoryListView, name='category-objects'),
    path('account/<str:user>/', MyAccountView, name="my-account"),
    path('subscribe/email/', EmailSub, name="subscribe"),
    path('compare/<user>/add-to-compare/<slug>/', add_to_compaire, name = 'add-to-compare'),
    path('query/', MainSearch, name='search'),
    path('products/tag/<slug>/', TagView, name="tag-view")
]

User/urls.py
from django.urls import path
from .views import (LogInView, LogOutView, RegisterView,
                    VerificationView, RequestResetEmail,
                    ResetPasswordView)

app_name = 'user'

urlpatterns = [
    path('register/', RegisterView, name='register'),
    path('login/', LogInView, name='login'),
    path('logout/', LogOutView, name='logout'),
    path('activate/<uidb64>/<token>/', VerificationView, name='activate'),
    path('request-reset-email/', RequestResetEmail, name="request-reset-email"),
    path('reset-password/<uidb64>/<token>/', ResetPasswordView, name='reset-password'),
]

frontend/templates/compare.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    | Compare Specs
{% endblock title %}

{% block message %}
    {% include 'partials/messages.html' %}
{% endblock message %}


{% block body %}
    

        <!-- breadcrumb area start -->
        <div class="breadcrumb-area">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="breadcrumb-wrap">
                            <nav aria-label="breadcrumb">
                                <ul class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{% url 'products:index' %}">Home</a></li>
                                    <li class="breadcrumb-item"><a href="{% url 'products:shop' %}">shop</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">compare</li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- breadcrumb area end -->

        <!-- compare main wrapper start -->
        <div class="compare-page-wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <!-- Compare Page Content Start -->
                        <div class="compare-page-content-wrap">
                            <div class="compare-table table-responsive">
                                <table class="table table-bordered mb-0">
                                    <tbody>
                                    <tr>
                                        <td class="first-column">Product</td>


                                        
                                        {% for product in compare_items %}
                                        <td class="product-image-title">
                                            <a href="{{ product.get_absolute_url }}" class="image">
                                                <img class="img-fluid" src="{{ product.image_thumbnail.url }}" alt="Compare Product">
                                            </a>
                                            <a href="#" class="category">{{ product.product_name }}</a>
                                            <a href="{% url 'products:category-objects' product.category.slug %}" class="title">{{ product.category.title }}</a>
                                            <a href="{% url 'products:shop-products' product.added_by_merchant.shop.slug %}" class="title">{{ product.added_by_merchant.shop.shop_name }}</a>
                                        </td>
                                        {% endfor %}
                                            
                                        
                                    </tr>
                                    <tr>
                                        <td class="first-column">Description</td>


                                        
                                        {% for product in compare_items %}
                                        <td class="pro-desc">
                                            <p>{{ product.product_description|safe }}</p>
                                        </td>
                                        {% endfor %}
                                            
                                        
                                    </tr>
                                    <tr>
                                        <td class="first-column">Price</td>

                                       
                                       {% for product in compare_items %}
                                         <td class="pro-price">Ksh. {{ product.product_discount_price }}</td>
                                       {% endfor %}
                                           
                                       
                                    </tr>
                                    <tr>
                                        <td class="first-column">Color</td>

                                        
                                        {% for product in compare_items %}
                                            <td class="pro-color">Black</td>
                                        {% endfor %}
                                            
                                        
                                    </tr>
                                    <tr>
                                        <td class="first-column">Stock</td>

                                        
                                        {% for product in compare_items %}
                                        <td class="pro-stock">In Stock</td>
                                        {% endfor %}
                                            

                                    </tr>
                                    <tr>
                                        <td class="first-column">Add to cart</td>
                                        
                                        {% for product in compare_items %}
                                        <td><a href="cart.html" class="sqr-btn">Add to Cart</a></td>
                                        {% endfor %}
                                            
                                        
                                    </tr>
                                    <tr>
                                        <td class="first-column">Rating</td>

                                        
                                        {% for product in compare_items %}
                                        <td class="pro-ratting">
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star-o"></i>
                                        </td>
                                        {% endfor %}
                                            
                                        
                                    </tr>
                                    <tr>
                                        <td class="first-column">Remove</td>

                                        
                                        {% for product in compare_items %}
                                        <td class="pro-remove">
                                            <button><i class="fa fa-trash-o"></i></button>
                                        </td>
                                        {% endfor %}
                                            
                                        
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- Compare Page Content End -->
                    </div>
                </div>
            </div>
        </div>
        <!-- compare main wrapper end -->

        <!-- brand area start -->
        {% include 'partials/brand.html' %}
        <!-- brand area end -->

        
{% endblock body %}
    

frontend/templates/contact-us.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
   | Contact Us
{% endblock title %}

{% block message %}
    {% include 'partials/messages.html' %}
{% endblock message %}
    

{% block body %}
    

        <!-- breadcrumb area start -->
        <div class="breadcrumb-area">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="breadcrumb-wrap">
                            <nav aria-label="breadcrumb">
                                <ul class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{% url 'products:index' %}">Home</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">contact us</li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- breadcrumb area end -->

        <!-- contact area start -->
        <div class="contact-area pb-34 pb-md-18 pb-sm-0">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="contact-message">
                            <h2>tell us your project</h2>
                            <form id="" action="{% url 'products:contact' %}" method="POST" class="contact-form">{% csrf_token %}
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <input name="name" placeholder="Name *" type="text" required>    
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <input name="phone" placeholder="Phone *" type="text" required>   
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <input name="email" placeholder="Email *" type="text" required>    
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <input name="subject" placeholder="Subject *" type="text">   
                                    </div>
                                <div class="col-12">
                                        <div class="contact2-textarea text-center">
                                            <textarea placeholder="Message *" name="message"  class="form-control2" required=""></textarea>     
                                        </div>   
                                        <div class="contact-btn">
                                            <button class="sqr-btn" type="submit">Send Message</button> 
                                        </div> 
                                    </div> 
                                </div>
                            </form>    
                        </div> 
                    </div>
                    <div class="col-lg-6">
                        <div class="contact-info mt-md-28 mt-sm-28">
                            <h2>contact us</h2>
                            <p>Reach us for futher assistance or for any queries.</p>
                            <ul>
                                <li><i class="fa fa-fax"></i> Address : 47 Mwatate Town 80305 Kenya</li>
                                <li><i class="fa fa-phone"></i> info@rmarket.com</li>
                                <li><i class="fa fa-envelope-o"></i> +254712860997</li>
                            </ul>
                            <div class="working-time">
                                <h3>Working hours</h3>
                                <p><span>Monday – Sunday:</span>24 hrs</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- contact area end -->

        <!-- map area start -->
        <div class="map-area-wrapper">
            <div class="container">
                    <div id="map_content" data-lat="23.763491" data-lng="90.431167" data-zoom="8" data-maptitle="R-Market" data-mapaddress="Floor# 4, House# 5, Block# C     </br> Voi - Taveta Rd, Mwatate">
                    </div>
            </div>
        </div>
        <!-- map area end -->

        <!-- brand area start -->
        <div class="brand-area pt-34 pb-30">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title mb-30">
                            <div class="title-icon">
                                <i class="fa fa-crop"></i>
                            </div>
                            <h3>Popular Brand</h3>
                        </div> <!-- section title end -->
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="brand-active slick-padding slick-arrow-style">
                            {% for brand in popular_brands %}
                                <div class="brand-item text-center">
                                    <a href="#"><img src="{{ brand.avatar_thumbnail.url }}" alt="{{brand.name}}"></a>
                                </div>
                             {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- brand area end -->

        
{% endblock body %}
    

frontend/templates/product-form.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    | Add Product
{% endblock title %}

{% block message %}
    {% include 'partials/messages.html' %}
{% endblock message %}

{% block body %}
    <!-- breadcrumb area start -->
 <div class="breadcrumb-area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb-wrap">
                    <nav aria-label="breadcrumb">
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'products:index' %}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Add Product</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- breadcrumb area end -->

<!-- login register wrapper start -->
<div class="login-register-wrapper">
    <div class="container">
        <div class="member-area-from-wrap">
            <div class="row">
                <!-- Login Content Start -->
                <div class="col-lg-12">
                    
                    <div class="login-reg-form-wrap  pr-lg-50">
                        <h2>Add Product</h2>
                            {% include 'partials/messages.html' %}
                        <form action="" enctype="multipart/form-data" method="POST">
                            {% csrf_token %}
                            {{  form.media }}
                            {{ form.as_p }}
                            <div class="mt-4">
                                <label for="product-media">Images</label>
                                <input type="file" multiple name="product-media" id="product-images" accept="image/*">
                            </div>
                           <br> <button class="btn btn-primary" type="submit">Post</button>
                        </form>
                    </div>
                </div>
                <!-- Login Content End -->

            </div>
        </div>
    </div>
</div>
<!-- login register wrapper end -->

<!-- brand area start -->
{% include 'partials/brand.html' %}
<!-- brand area end -->
 
{% endblock body %}
    

frontend/templates/shop-list.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
   | Shops
{% endblock title %}

{% block message %}
    {% include 'partials/messages.html' %}
{% endblock message %}

{% block body %}
    

        <!-- home banner area start -->
        <div class="banner-area mt-30">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-3 col-sm-6 order-1">
                        <div class="img-container img-full fix imgs-res mb-sm-30">
                            <a href="#">
                                <img src="{% static 'assets/img/banner/banner_left.jpg' %}" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-5 col-md-5 order-sm-3">
                        <div class="img-container img-full fix mb-30">
                            <a href="#">
                                <img src="{% static 'assets/img/banner/banner_static_top1.jpg' %}" alt="">
                            </a>
                        </div>
                        <div class="img-container img-full fix mb-30">
                            <a href="#">
                                <img src="{% static 'assets/img/banner/banner_static_top2.jpg' %}" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-6 order-2 order-md-3">
                        <div class="img-container img-full fix">
                            <a href="#">
                                <img src="{% static 'assets/img/banner/banner_static_top3.jpg' %}" alt="">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- home banner area end -->


        <!-- latest product start -->
        
        {% for shop in shops %}
        <div class="latest-product">
            <div class="container">
                <div class="section-title mb-30">
                    <div class="title-icon">
                        <i class="fa fa-flash"></i>
                    </div>
                    <h3><a href="{% url 'products:shop-products' shop.slug %}">{{ shop.shop_name }}</a></h3>
                </div> <!-- section title end -->
                <!-- featured category start -->
                <div class="latest-product-active slick-padding slick-arrow-style">
                    <!-- product single item start -->
                    
                    
                    {% for product in new_arrivals %}
                        <div class="product-item fix">
                            <div class="product-thumb">
                                <a href="{% url 'products:product-detail' product.slug %}">
                                    <img src="{{ product.image_thumbnail.url }}" class="img-pri" alt="">
                                    
                                </a>
                                <div class="product-label">
                                    <span>hot</span>
                                </div>
                                <div class="product-action-link">
                                    <a href="#" data-toggle="modal" data-target="#quick_view"> <span data-toggle="tooltip"
                                            data-placement="left" title="Quick view"><i class="fa fa-search"></i></span>
                                    </a>
                                    <a href="#" data-toggle="tooltip" data-placement="left" title="Wishlist"><i class="fa fa-heart-o"></i></a>
                                    <a href="#" data-toggle="tooltip" data-placement="left" title="Compare"><i class="fa fa-refresh"></i></a>
                                    <a href="#" data-toggle="tooltip" data-placement="left" title="Add to cart"><i class="fa fa-shopping-cart"></i></a>
                                </div>
                            </div>
                            <div class="product-content">
                                <h4><a href="{% url 'products:product-detail' product.slug %}">{{ product.product_name }}</a></h4>
                                <div class="pricebox">
                                    <span class="regular-price">Ksh. {{ product.product_discount_price }}</span>
                                    <div class="ratings">
                                        <span class="good"><i class="fa fa-star"></i></span>
                                        <span class="good"><i class="fa fa-star"></i></span>
                                        <span class="good"><i class="fa fa-star"></i></span>
                                        <span class="good"><i class="fa fa-star"></i></span>
                                        <span><i class="fa fa-star"></i></span>
                                        <div class="pro-review">
                                            <span>1 review(s)</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                      


                    <!-- product single item end -->
                    <!-- product single item start -->
                    
                </div>
                <!-- featured category end -->
            </div>
        </div>
        <!-- latest product end -->
        <!-- banner statistic start -->
        <div class="banner-statistic pt-28 pb-36">
            <div class="img-container fix img-full">
                <a href="#">
                    <img src="{% static 'assets/img/banner/banner_static1.jpg' %}" alt="">
                </a>
            </div>
        </div>
        <!-- banner statistic end -->
        {% endfor %}
           
        

        {% include 'partials/brand.html' %}


{% endblock body %}
    

frontend/templates/wishlist.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    wishlist
{% endblock title %}

{% block message %}
    {% include 'partials/messages.html' %}
{% endblock message %}


{% block body %}
    <!-- breadcrumb area start -->
    <div class="breadcrumb-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumb-wrap">
                        <nav aria-label="breadcrumb">
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{% url 'products:index' %}">Home</a></li>
                                <li class="breadcrumb-item"><a href="{% url 'products:shop' %}">shop</a></li>
                                <li class="breadcrumb-item active" aria-current="page">checkout</li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- breadcrumb area end -->

    <!-- wishlist main wrapper start -->
    <div class="wishlist-main-wrapper">
        <div class="container">
            <!-- Wishlist Page Content Start -->
            <div class="row">
                <div class="col-lg-12">
                    <!-- Wishlist Table Area -->
                    <div class="cart-table table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th class="pro-thumbnail">Thumbnail</th>
                                <th class="pro-title">Product</th>
                                <th class="pro-price">Price</th>
                                <th class="pro-quantity">Stock Status</th>
                                <th class="pro-subtotal">Add to Cart</th>
                                <th class="pro-remove">Remove</th>
                            </tr>
                            </thead>
                            <tbody>


                            
                            {% for product in wishlist_items.products.all %}
                            <tr>
                                <td class="pro-thumbnail"><a href="#"><img class="img-fluid" src="{{ product.product.image_thumbnail.url }}"
                                                                            alt="Product"/></a></td>
                                <td class="pro-title"><a href="#">{{ product.product.product_name }}</a></td>
                                <td class="pro-price"><span>Ksh. {{ product.product.product_discount_price }}</span></td>
                                <td class="pro-quantity"><span class="text-success">In Stock</span></td>
                                <td class="pro-subtotal"><a href="{% url 'products:add-to-cart' product.product.slug %}" class="sqr-btn text-white">Add to Cart</a></td>
                                <td class="pro-remove"><a href="#"><i class="fa fa-trash-o"></i></a></td>
                            </tr>
                            {% endfor %}
                                
                            
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- Wishlist Page Content End -->
        </div>
    </div>
    <!-- wishlist main wrapper end -->

    <!-- brand area start -->
    {% include 'partials/brand.html' %}
    <!-- brand area end -->

{% endblock body %}
    
    
    